#!/usr/bin/python2.7
# Part of info-beamer hosted. You can find the latest version
# of this file at:

import mqtt_helper
import ibquery
import time

ib = ibquery.InfoBeamerQuery()
s = ib.node('root').io(raw=True)

    
while True:

    asset_name= s.readline()
    print(asset_name) # this should read the value sent in client_write above
    print(mqtt_helper.send_data_to_adafruit_io('current-asset-name', str(asset_name)))
    
    # REMOVE LATER XXXXX
    time.sleep(10)

